services:
  frontend:
    build:
      context: ../frontend
      args:
        REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - web

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_CONNECTION_STRING: postgres://mental_user:mental_pass@db:5432/mental_db?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mental_db
      POSTGRES_USER: mental_user
      POSTGRES_PASSWORD: mental_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mental_user -d mental_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: